// <copyright file="Game1.cs" company="YourCompanyName">
// Copyright (c) YourCompanyName. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <autogenerated/>

internal class Program
{
    private static void Main(string[] args)
    {
        using var game = new Project1.GameManager(true);
        game.Run();
    }
}