// <copyright file="Game1.cs" company="YourCompanyName">
// Copyright (c) YourCompanyName. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <autogenerated/>

using NUnit.Framework;
using Project1;

namespace Project1.Tests
{
    [TestFixture]
    public class ProgramTests
    {
        [Test]
        public void Main_ShouldCreateAndRunTestGameManagerWithoutOpeningWindow()
        {
            var testGameManager = new TestGameManager();

            testGameManager.Run();

            Assert.Pass("Test passed without GUI.");
        }
    }
}
