// <copyright file="Game1.cs" company="YourCompanyName">
// Copyright (c) YourCompanyName. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>
// <autogenerated/>

namespace Project1.Tests
{
    using System;

    /// <summary>
    /// Needed for testing.
    /// </summary>
    public class TestGameManager : GameManager
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestGameManager"/> class.
        /// </summary>
        public TestGameManager()
            : base(false) // Testmodus aktivieren
        {
        }

        /// <summary>
        /// Simulating "Run()".
        /// </summary>
        public new virtual void Run()
        {
            SimulateGameLogic();
        }

        private static void SimulateGameLogic()
        {
            Console.WriteLine("Simulating game logic for testing.");
        }
    }
}